import { cva } from "class-variance-authority";
import { twMerge } from "tailwind-merge";
import { ButtonProps } from "./types";
import React from "react";

const Button: React.FC<ButtonProps> = ({
  className,
  width,
  height,
  value,
  px,
  toggle,
  mode,
  gap,
  size,
  shape,
  loading,
  icon,
  arrow,
  outline,
  variant,
  chidlren,
  bezel,
  disabled,
  type,
  onClick,
  ...props
}) => {
  // const StyleButton = styled.button` width: ${width}; background-color: ${backgroundColor}; `
  const StyleButton = cva(
    [
      "button",
      `${mode === "switch" ? "justify-start" : "justify-center"}`,
      `${
        disabled
          ? "cursor-not-allowed disabled:opacity-60 pointer-events-none"
          : "cursor-pointer"
      }`,
      `${bezel ? "bg-gradient-to-r border-none" : "border"}`,
    ],
    {
      variants: {
        size: {
          xs: "size-6",
          sm: "size-7",
          md: "size-8",
          lg: "size-9",
          xl: "size-10",
        },
        toggle: {
          xs: "w-9 h-5",
          sm: "w-10 h-6",
          md: "w-11 h-6",
          lg: "w-12 h-7",
          xl: "w-14 h-8",
        },
        px: {
          xs: "px-2",
          sm: "px-4",
          md: "px-6",
          lg: "px-8",
          xl: "px-10",
        },
        height: {
          xs: "h-6",
          sm: "h-7",
          md: "h-8",
          lg: "h-9",
          xl: "h-10",
        },
        width: {
          full: "w-full",
          xs: "w-fit",
          sm: "",
          md: "",
          lg: "",
          xl: "",
        },
        shape: {
          default: "rounded-md",
          circle: "rounded-full",
          square: "rounded-lg",
          rounded: "rounded-md",
        },
        loading: { default: false, true: true, false: false },
        mode: { switch: "toggle-switch", menu: "toggle-menu" },
        gap: {
          1: "gap-1",
          2: "gap-2",
          3: "gap-3",
          4: "gap-4",
          5: "gap-5",
          6: "gap-6",
          7: "gap-7",
          8: "gap-8",
          9: "gap-9",
          10: "gap-10",
        },
        variant: {
          info: [
            "bg-black",
            "border-black",
            "text-white",
            "hover:bg-info-900",
            "hover:border-info-900",
            "hover:text-info-100",
            "active:bg-info-700",
            "active:border-info-700",
            "active:text-white",
            "disabled:bg-info-300",
            "disabled:border-info-300",
            "disabled:text-info-200",
            "dark:bg-white",
            "dark:border-white",
            "dark:text-black",
            "dark:hover:bg-info-600",
            "dark:hover:border-info-600",
            "dark:hover:text-info-100",
            "dark:active:bg-info-800",
            "dark:active:border-info-800",
            "dark:disabled:bg-info-200",
            "dark:disabled:border-info-200",
            "dark:disabled:text-info-300",
          ],
          danger: [
            "bg-danger-500",
            "border-danger-500",
            "text-danger-50",
            "hover:bg-danger-600",
            "hover:border-danger-600",
            "hover:text-danger-100",
            "active:bg-danger-700",
            "active:border-danger-700",
            "active:text-white",
            "disabled:bg-danger-300",
            "disabled:border-danger-300",
            "disabled:text-danger-200",
            "dark:bg-danger-700",
            "dark:border-danger-700",
            "dark:text-white",
            "dark:hover:bg-danger-600",
            "dark:hover:border-danger-600",
            "dark:hover:text-danger-100",
            "dark:active:bg-danger-800",
            "dark:active:border-danger-800",
            "dark:disabled:bg-danger-200",
            "dark:disabled:border-danger-200",
            "dark:disabled:text-danger-300",
          ],
          primary: [
            "bg-primary-500",
            "border-primary-500",
            "text-primary-50",
            "hover:bg-primary-600",
            "hover:border-primary-600",
            "hover:text-primary-100",
            "active:bg-primary-700",
            "active:border-primary-700",
            "active:text-white",
            "disabled:bg-primary-300",
            "disabled:border-primary-300",
            "disabled:text-primary-200",
            "dark:bg-primary-700",
            "dark:border-primary-700",
            "dark:text-white",
            "dark:hover:bg-primary-600",
            "dark:hover:border-primary-600",
            "dark:hover:text-primary-100",
            "dark:active:bg-primary-800",
            "dark:active:border-primary-800",
            "dark:disabled:bg-primary-200",
            "dark:disabled:border-primary-200",
            "dark:disabled:text-primary-300",
          ],
          success: [
            "bg-success-500",
            "border-success-500",
            "text-success-50",
            "hover:bg-success-600",
            "hover:border-success-600",
            "hover:text-success-100",
            "active:bg-success-700",
            "active:border-success-700",
            "active:text-white",
            "disabled:bg-success-300",
            "disabled:border-success-300",
            "disabled:text-success-200",
            "dark:bg-success-700",
            "dark:border-success-700",
            "dark:text-white",
            "dark:hover:bg-success-600",
            "dark:hover:border-success-600",
            "dark:hover:text-success-100",
            "dark:active:bg-success-800",
            "dark:active:border-success-800",
            "dark:disabled:bg-success-200",
            "dark:disabled:border-success-200",
            "dark:disabled:text-success-300",
          ],
          warning: [
            "bg-warning-500",
            "border-warning-500",
            "text-warning-50",
            "hover:bg-warning-600",
            "hover:border-warning-600",
            "hover:text-warning-100",
            "active:bg-warning-700",
            "active:border-warning-700",
            "active:text-white",
            "disabled:bg-warning-300",
            "disabled:border-warning-300",
            "disabled:text-warning-200",
            "dark:bg-warning-700",
            "dark:border-warning-700",
            "dark:text-white",
            "dark:hover:bg-warning-600",
            "dark:hover:border-warning-600",
            "dark:hover:text-warning-100",
            "dark:active:bg-warning-800",
            "dark:active:border-warning-800",
            "dark:disabled:bg-warning-200",
            "dark:disabled:border-warning-200",
            "dark:disabled:text-warning-300",
          ],
          japanese: [
            "bg-japanese-500",
            "border-japanese-500",
            "text-japanese-50",
            "hover:bg-japanese-600",
            "hover:border-japanese-600",
            "hover:text-japanese-100",
            "active:bg-japanese-700",
            "active:border-japanese-700",
            "active:text-white",
            "disabled:bg-japanese-300",
            "disabled:border-japanese-300",
            "disabled:text-japanese-200",
            "dark:bg-japanese-700",
            "dark:border-japanese-700",
            "dark:text-white",
            "dark:hover:bg-japanese-600",
            "dark:hover:border-japanese-600",
            "dark:hover:text-japanese-100",
            "dark:active:bg-japanese-800",
            "dark:active:border-japanese-800",
            "dark:disabled:bg-japanese-200",
            "dark:disabled:border-japanese-200",
            "dark:disabled:text-japanese-300",
          ],
          slate: [
            "bg-slate-500",
            "border-slate-500",
            "text-slate-50",
            "hover:bg-slate-600",
            "hover:border-slate-600",
            "hover:text-slate-100",
            "active:bg-slate-700",
            "active:border-slate-700",
            "active:text-white",
            "disabled:bg-slate-300",
            "disabled:border-slate-300",
            "disabled:text-slate-200",
            "dark:bg-slate-700",
            "dark:border-slate-700",
            "dark:text-white",
            "dark:hover:bg-slate-600",
            "dark:hover:border-slate-600",
            "dark:hover:text-slate-100",
            "dark:active:bg-slate-800",
            "dark:active:border-slate-800",
            "dark:disabled:bg-slate-200",
            "dark:disabled:border-slate-200",
            "dark:disabled:text-slate-300",
          ],
          gray: [
            "bg-gray-500",
            "border-gray-500",
            "text-gray-50",
            "hover:bg-gray-600",
            "hover:border-gray-600",
            "hover:text-gray-100",
            "active:bg-gray-700",
            "active:border-gray-700",
            "active:text-white",
            "disabled:bg-gray-300",
            "disabled:border-gray-300",
            "disabled:text-gray-200",
            "dark:bg-gray-700",
            "dark:border-gray-700",
            "dark:text-white",
            "dark:hover:bg-gray-600",
            "dark:hover:border-gray-600",
            "dark:hover:text-gray-100",
            "dark:active:bg-gray-800",
            "dark:active:border-gray-800",
            "dark:disabled:bg-gray-200",
            "dark:disabled:border-gray-200",
            "dark:disabled:text-gray-300",
          ],
          zinc: [
            "bg-zinc-500",
            "border-zinc-500",
            "text-zinc-50",
            "hover:bg-zinc-600",
            "hover:border-zinc-600",
            "hover:text-zinc-100",
            "active:bg-zinc-700",
            "active:border-zinc-700",
            "active:text-white",
            "disabled:bg-zinc-300",
            "disabled:border-zinc-300",
            "disabled:text-zinc-200",
            "dark:bg-zinc-700",
            "dark:border-zinc-700",
            "dark:text-white",
            "dark:hover:bg-zinc-600",
            "dark:hover:border-zinc-600",
            "dark:hover:text-zinc-100",
            "dark:active:bg-zinc-800",
            "dark:active:border-zinc-800",
            "dark:disabled:bg-zinc-200",
            "dark:disabled:border-zinc-200",
            "dark:disabled:text-zinc-300",
          ],
          neutral: [
            "bg-neutral-500",
            "border-neutral-500",
            "text-neutral-50",
            "hover:bg-neutral-600",
            "hover:border-neutral-600",
            "hover:text-neutral-100",
            "active:bg-neutral-700",
            "active:border-neutral-700",
            "active:text-white",
            "disabled:bg-neutral-300",
            "disabled:border-neutral-300",
            "disabled:text-neutral-200",
            "dark:bg-neutral-700",
            "dark:border-neutral-700",
            "dark:text-white",
            "dark:hover:bg-neutral-600",
            "dark:hover:border-neutral-600",
            "dark:hover:text-neutral-100",
            "dark:active:bg-neutral-800",
            "dark:active:border-neutral-800",
            "dark:disabled:bg-neutral-200",
            "dark:disabled:border-neutral-200",
            "dark:disabled:text-neutral-300",
          ],
          stone: [
            "bg-stone-500",
            "border-stone-500",
            "text-stone-50",
            "hover:bg-stone-600",
            "hover:border-stone-600",
            "hover:text-stone-100",
            "active:bg-stone-700",
            "active:border-stone-700",
            "active:text-white",
            "disabled:bg-stone-300",
            "disabled:border-stone-300",
            "disabled:text-stone-200",
            "dark:bg-stone-700",
            "dark:border-stone-700",
            "dark:text-white",
            "dark:hover:bg-stone-600",
            "dark:hover:border-stone-600",
            "dark:hover:text-stone-100",
            "dark:active:bg-stone-800",
            "dark:active:border-stone-800",
            "dark:disabled:bg-stone-200",
            "dark:disabled:border-stone-200",
            "dark:disabled:text-stone-300",
          ],
          red: [
            "bg-red-500",
            "border-red-500",
            "text-red-50",
            "hover:bg-red-600",
            "hover:border-red-600",
            "hover:text-red-100",
            "active:bg-red-700",
            "active:border-red-700",
            "active:text-white",
            "disabled:bg-red-300",
            "disabled:border-red-300",
            "disabled:text-red-200",
            "dark:bg-red-700",
            "dark:border-red-700",
            "dark:text-white",
            "dark:hover:bg-red-600",
            "dark:hover:border-red-600",
            "dark:hover:text-red-100",
            "dark:active:bg-red-800",
            "dark:active:border-red-800",
            "dark:disabled:bg-red-200",
            "dark:disabled:border-red-200",
            "dark:disabled:text-red-300",
          ],
          orange: [
            "bg-orange-500",
            "border-orange-500",
            "text-orange-50",
            "hover:bg-orange-600",
            "hover:border-orange-600",
            "hover:text-orange-100",
            "active:bg-orange-700",
            "active:border-orange-700",
            "active:text-white",
            "disabled:bg-orange-300",
            "disabled:border-orange-300",
            "disabled:text-orange-200",
            "dark:bg-orange-700",
            "dark:border-orange-700",
            "dark:text-white",
            "dark:hover:bg-orange-600",
            "dark:hover:border-orange-600",
            "dark:hover:text-orange-100",
            "dark:active:bg-orange-800",
            "dark:active:border-orange-800",
            "dark:disabled:bg-orange-200",
            "dark:disabled:border-orange-200",
            "dark:disabled:text-orange-300",
          ],
          amber: [
            "bg-amber-500",
            "border-amber-500",
            "text-amber-50",
            "hover:bg-amber-600",
            "hover:border-amber-600",
            "hover:text-amber-100",
            "active:bg-amber-700",
            "active:border-amber-700",
            "active:text-white",
            "disabled:bg-amber-300",
            "disabled:border-amber-300",
            "disabled:text-amber-200",
            "dark:bg-amber-700",
            "dark:border-amber-700",
            "dark:text-white",
            "dark:hover:bg-amber-600",
            "dark:hover:border-amber-600",
            "dark:hover:text-amber-100",
            "dark:active:bg-amber-800",
            "dark:active:border-amber-800",
            "dark:disabled:bg-amber-200",
            "dark:disabled:border-amber-200",
            "dark:disabled:text-amber-300",
          ],
          yellow: [
            "bg-yellow-500",
            "border-yellow-500",
            "text-yellow-50",
            "hover:bg-yellow-600",
            "hover:border-yellow-600",
            "hover:text-yellow-100",
            "active:bg-yellow-700",
            "active:border-yellow-700",
            "active:text-white",
            "disabled:bg-yellow-300",
            "disabled:border-yellow-300",
            "disabled:text-yellow-200",
            "dark:bg-yellow-700",
            "dark:border-yellow-700",
            "dark:text-white",
            "dark:hover:bg-yellow-600",
            "dark:hover:border-yellow-600",
            "dark:hover:text-yellow-100",
            "dark:active:bg-yellow-800",
            "dark:active:border-yellow-800",
            "dark:disabled:bg-yellow-200",
            "dark:disabled:border-yellow-200",
            "dark:disabled:text-yellow-300",
          ],
          lime: [
            "bg-lime-500",
            "border-lime-500",
            "text-lime-50",
            "hover:bg-lime-600",
            "hover:border-lime-600",
            "hover:text-lime-100",
            "active:bg-lime-700",
            "active:border-lime-700",
            "active:text-white",
            "disabled:bg-lime-300",
            "disabled:border-lime-300",
            "disabled:text-lime-200",
            "dark:bg-lime-700",
            "dark:border-lime-700",
            "dark:text-white",
            "dark:hover:bg-lime-600",
            "dark:hover:border-lime-600",
            "dark:hover:text-lime-100",
            "dark:active:bg-lime-800",
            "dark:active:border-lime-800",
            "dark:disabled:bg-lime-200",
            "dark:disabled:border-lime-200",
            "dark:disabled:text-lime-300",
          ],
          green: [
            "bg-green-500",
            "border-green-500",
            "text-green-50",
            "hover:bg-green-600",
            "hover:border-green-600",
            "hover:text-green-100",
            "active:bg-green-700",
            "active:border-green-700",
            "active:text-white",
            "disabled:bg-green-300",
            "disabled:border-green-300",
            "disabled:text-green-200",
            "dark:bg-green-700",
            "dark:border-green-700",
            "dark:text-white",
            "dark:hover:bg-green-600",
            "dark:hover:border-green-600",
            "dark:hover:text-green-100",
            "dark:active:bg-green-800",
            "dark:active:border-green-800",
            "dark:disabled:bg-green-200",
            "dark:disabled:border-green-200",
            "dark:disabled:text-green-300",
          ],
          emerald: [
            "bg-emerald-500",
            "border-emerald-500",
            "text-emerald-50",
            "hover:bg-emerald-600",
            "hover:border-emerald-600",
            "hover:text-emerald-100",
            "active:bg-emerald-700",
            "active:border-emerald-700",
            "active:text-white",
            "disabled:bg-emerald-300",
            "disabled:border-emerald-300",
            "disabled:text-emerald-200",
            "dark:bg-emerald-700",
            "dark:border-emerald-700",
            "dark:text-white",
            "dark:hover:bg-emerald-600",
            "dark:hover:border-emerald-600",
            "dark:hover:text-emerald-100",
            "dark:active:bg-emerald-800",
            "dark:active:border-emerald-800",
            "dark:disabled:bg-emerald-200",
            "dark:disabled:border-emerald-200",
            "dark:disabled:text-emerald-300",
          ],
          teal: [
            "bg-teal-500",
            "border-teal-500",
            "text-teal-50",
            "hover:bg-teal-600",
            "hover:border-teal-600",
            "hover:text-teal-100",
            "active:bg-teal-700",
            "active:border-teal-700",
            "active:text-white",
            "disabled:bg-teal-300",
            "disabled:border-teal-300",
            "disabled:text-teal-200",
            "dark:bg-teal-700",
            "dark:border-teal-700",
            "dark:text-white",
            "dark:hover:bg-teal-600",
            "dark:hover:border-teal-600",
            "dark:hover:text-teal-100",
            "dark:active:bg-teal-800",
            "dark:active:border-teal-800",
            "dark:disabled:bg-teal-200",
            "dark:disabled:border-teal-200",
            "dark:disabled:text-teal-300",
          ],
          cyan: [
            "bg-cyan-500",
            "border-cyan-500",
            "text-cyan-50",
            "hover:bg-cyan-600",
            "hover:border-cyan-600",
            "hover:text-cyan-100",
            "active:bg-cyan-700",
            "active:border-cyan-700",
            "active:text-white",
            "disabled:bg-cyan-300",
            "disabled:border-cyan-300",
            "disabled:text-cyan-200",
            "dark:bg-cyan-700",
            "dark:border-cyan-700",
            "dark:text-white",
            "dark:hover:bg-cyan-600",
            "dark:hover:border-cyan-600",
            "dark:hover:text-cyan-100",
            "dark:active:bg-cyan-800",
            "dark:active:border-cyan-800",
            "dark:disabled:bg-cyan-200",
            "dark:disabled:border-cyan-200",
            "dark:disabled:text-cyan-300",
          ],
          sky: [
            "bg-sky-500",
            "border-sky-500",
            "text-sky-50",
            "hover:bg-sky-600",
            "hover:border-sky-600",
            "hover:text-sky-100",
            "active:bg-sky-700",
            "active:border-sky-700",
            "active:text-white",
            "disabled:bg-sky-300",
            "disabled:border-sky-300",
            "disabled:text-sky-200",
            "dark:bg-sky-700",
            "dark:border-sky-700",
            "dark:text-white",
            "dark:hover:bg-sky-600",
            "dark:hover:border-sky-600",
            "dark:hover:text-sky-100",
            "dark:active:bg-sky-800",
            "dark:active:border-sky-800",
            "dark:disabled:bg-sky-200",
            "dark:disabled:border-sky-200",
            "dark:disabled:text-sky-300",
          ],
          blue: [
            "bg-blue-500",
            "border-blue-500",
            "text-blue-50",
            "hover:bg-blue-600",
            "hover:border-blue-600",
            "hover:text-blue-100",
            "active:bg-blue-700",
            "active:border-blue-700",
            "active:text-white",
            "disabled:bg-blue-300",
            "disabled:border-blue-300",
            "disabled:text-blue-200",
            "dark:bg-blue-700",
            "dark:border-blue-700",
            "dark:text-white",
            "dark:hover:bg-blue-600",
            "dark:hover:border-blue-600",
            "dark:hover:text-blue-100",
            "dark:active:bg-blue-800",
            "dark:active:border-blue-800",
            "dark:disabled:bg-blue-200",
            "dark:disabled:border-blue-200",
            "dark:disabled:text-blue-300",
          ],
          indigo: [
            "bg-indigo-500",
            "border-indigo-500",
            "text-indigo-50",
            "hover:bg-indigo-600",
            "hover:border-indigo-600",
            "hover:text-indigo-100",
            "active:bg-indigo-700",
            "active:border-indigo-700",
            "active:text-white",
            "disabled:bg-indigo-300",
            "disabled:border-indigo-300",
            "disabled:text-indigo-200",
            "dark:bg-indigo-700",
            "dark:border-indigo-700",
            "dark:text-white",
            "dark:hover:bg-indigo-600",
            "dark:hover:border-indigo-600",
            "dark:hover:text-indigo-100",
            "dark:active:bg-indigo-800",
            "dark:active:border-indigo-800",
            "dark:disabled:bg-indigo-200",
            "dark:disabled:border-indigo-200",
            "dark:disabled:text-indigo-300",
          ],
          violet: [
            "bg-violet-500",
            "border-violet-500",
            "text-violet-50",
            "hover:bg-violet-600",
            "hover:border-violet-600",
            "hover:text-violet-100",
            "active:bg-violet-700",
            "active:border-violet-700",
            "active:text-white",
            "disabled:bg-violet-300",
            "disabled:border-violet-300",
            "disabled:text-violet-200",
            "dark:bg-violet-700",
            "dark:border-violet-700",
            "dark:text-white",
            "dark:hover:bg-violet-600",
            "dark:hover:border-violet-600",
            "dark:hover:text-violet-100",
            "dark:active:bg-violet-800",
            "dark:active:border-violet-800",
            "dark:disabled:bg-violet-200",
            "dark:disabled:border-violet-200",
            "dark:disabled:text-violet-300",
          ],
          purple: [
            "bg-purple-500",
            "border-purple-500",
            "text-purple-50",
            "hover:bg-purple-600",
            "hover:border-purple-600",
            "hover:text-purple-100",
            "active:bg-purple-700",
            "active:border-purple-700",
            "active:text-white",
            "disabled:bg-purple-300",
            "disabled:border-purple-300",
            "disabled:text-purple-200",
            "dark:bg-purple-700",
            "dark:border-purple-700",
            "dark:text-white",
            "dark:hover:bg-purple-600",
            "dark:hover:border-purple-600",
            "dark:hover:text-purple-100",
            "dark:active:bg-purple-800",
            "dark:active:border-purple-800",
            "dark:disabled:bg-purple-200",
            "dark:disabled:border-purple-200",
            "dark:disabled:text-purple-300",
          ],
          fuchsia: [
            "bg-fuchsia-500",
            "border-fuchsia-500",
            "text-fuchsia-50",
            "hover:bg-fuchsia-600",
            "hover:border-fuchsia-600",
            "hover:text-fuchsia-100",
            "active:bg-fuchsia-700",
            "active:border-fuchsia-700",
            "active:text-white",
            "disabled:bg-fuchsia-300",
            "disabled:border-fuchsia-300",
            "disabled:text-fuchsia-200",
            "dark:bg-fuchsia-700",
            "dark:border-fuchsia-700",
            "dark:text-white",
            "dark:hover:bg-fuchsia-600",
            "dark:hover:border-fuchsia-600",
            "dark:hover:text-fuchsia-100",
            "dark:active:bg-fuchsia-800",
            "dark:active:border-fuchsia-800",
            "dark:disabled:bg-fuchsia-200",
            "dark:disabled:border-fuchsia-200",
            "dark:disabled:text-fuchsia-300",
          ],
          pink: [
            "bg-pink-500",
            "border-pink-500",
            "text-pink-50",
            "hover:bg-pink-600",
            "hover:border-pink-600",
            "hover:text-pink-100",
            "active:bg-pink-700",
            "active:border-pink-700",
            "active:text-white",
            "disabled:bg-pink-300",
            "disabled:border-pink-300",
            "disabled:text-pink-200",
            "dark:bg-pink-700",
            "dark:border-pink-700",
            "dark:text-white",
            "dark:hover:bg-pink-600",
            "dark:hover:border-pink-600",
            "dark:hover:text-pink-100",
            "dark:active:bg-pink-800",
            "dark:active:border-pink-800",
            "dark:disabled:bg-pink-200",
            "dark:disabled:border-pink-200",
            "dark:disabled:text-pink-300",
          ],
          rose: [
            "bg-rose-500",
            "border-rose-500",
            "text-rose-50",
            "hover:bg-rose-600",
            "hover:border-rose-600",
            "hover:text-rose-100",
            "active:bg-rose-700",
            "active:border-rose-700",
            "active:text-white",
            "disabled:bg-rose-300",
            "disabled:border-rose-300",
            "disabled:text-rose-200",
            "dark:bg-rose-700",
            "dark:border-rose-700",
            "dark:text-white",
            "dark:hover:bg-rose-600",
            "dark:hover:border-rose-600",
            "dark:hover:text-rose-100",
            "dark:active:bg-rose-800",
            "dark:active:border-rose-800",
            "dark:disabled:bg-rose-200",
            "dark:disabled:border-rose-200",
            "dark:disabled:text-rose-300",
          ],
        },
        bezel: {
          metal: [
            "from-info-500 to-stone-900",
            "hover:from-info-600 hover:to-stone-800",
            "active:from-info-700 active:to-stone-700",
          ],
          hibiscus: [
            "from-danger-500 to-red-900",
            "hover:from-danger-600 hover:to-red-800",
            "active:from-danger-700 active:to-red-700",
          ],
          clematis: [
            "from-violet-600 to-indigo-600",
            "hover:from-violet-700 hover:to-primary-700",
            "active:from-violet-800 active:to-primary-800",
          ],
          clear: [
            "from-success-500 to-emerald-900",
            "hover:from-success-600 hover:to-emerald-800",
            "active:from-success-700 active:to-emerald-700",
          ],
          snowflake: [
            "from-indigo-400 to-cyan-400",
            "hover:from-indigo-500 hover:to-cyan-500",
            "active:from-indigo-600 active:to-cyan-600",
          ],
          tree: [
            "from-emerald-500 to-emerald-900",
            "hover:from-emerald-800 hover:to-cyan-600",
            "active:from-emerald-700 active:to-cyan-700",
          ],
          cold: [
            "from-slate-300 to-slate-500",
            "hover:from-slate-400 hover:to-slate-400",
            "active:from-slate-500 active:to-slate-500",
          ],
          darkness: [
            "from-slate-900 to-slate-700",
            "hover:from-slate-800 hover:to-slate-600",
            "active:from-slate-700 active:to-slate-500",
          ],
          silver: [
            "from-slate-300 to-slate-500",
            "hover:from-slate-400 hover:to-slate-400",
            "active:from-slate-500 active:to-slate-500",
          ],
          clay: [
            "from-neutral-300 to-stone-400",
            "hover:from-neutral-400 hover:to-neutral-500",
            "active:from-neutral-500 active:to-neutral-600",
          ],
          soil: [
            "from-stone-500 to-stone-700",
            "hover:from-stone-600 hover:to-stone-400",
            "active:from-stone-700 active:to-stone-500",
          ],
          sunset: [
            "from-red-500 to-orange-500",
            "hover:from-red-600 hover:to-orange-600",
            "active:from-red-700 active:to-orange-700",
          ],
          gold: [
            "from-warning-500 to-orange-500",
            "hover:from-warning-600 hover:to-orange-600",
            "active:from-warning-700 active:to-orange-700",
          ],
          twilight: [
            "from-amber-500 to-pink-500",
            "hover:from-amber-600 hover:to-pink-600",
            "active:from-amber-700 active:to-pink-700",
          ],
          sunshine: [
            "from-amber-200 to-yellow-400",
            "hover:from-amber-300 hover:to-yellow-300",
            "active:from-amber-400 active:to-yellow-400",
          ],
          lime: [
            "from-teal-400 to-yellow-200",
            "hover:from-teal-500 hover:to-yellow-300",
            "active:from-teal-600 active:to-yellow-400",
          ],
          powder: [
            "from-warning-500 to-japanese-500",
            "hover:from-warning-600 hover:to-japanese-600",
            "active:from-warning-700 active:to-japanese-700",
          ],
          nemesia: [
            "from-emerald-400 to-cyan-400",
            "hover:from-emerald-500 hover:to-cyan-500",
            "active:from-emerald-600 active:to-cyan-600",
          ],
          light: [
            "from-teal-200 to-teal-500",
            "hover:from-teal-300 hover:to-teal-600",
            "active:from-teal-400 active:to-teal-700",
          ],
          holly: [
            "from-blue-200 to-cyan-200",
            "hover:from-blue-300 hover:to-cyan-300",
            "active:from-blue-400 active:to-cyan-400",
          ],
          salvia: [
            "from-fuchsia-500 to-cyan-500",
            "hover:from-fuchsia-600 hover:to-cyan-600",
            "active:from-fuchsia-700 active:to-cyan-700",
          ],
          bird: [
            "from-cyan-500 to-blue-500",
            "hover:from-cyan-600 hover:to-blue-600",
            "active:from-cyan-700 active:to-blue-700",
          ],
          amaranthus: [
            "from-fuchsia-600 to-purple-600",
            // "from-fuchsia-600 to-purple-600 bg-clip-text text-transparent",
            "hover:from-fuchsia-700 hover:to-purple-700",
            "active:from-fuchsia-800 active:to-purple-800",
          ],
          night: [
            "from-blue-600 to-violet-600",
            "hover:from-blue-700 hover:to-violet-700",
            "active:from-blue-800 active:to-violet-800",
          ],
          heartsease: [
            "from-fuchsia-600 to-purple-600",
            "hover:from-fuchsia-700 hover:to-purple-700",
            "active:from-fuchsia-800 active:to-purple-800",
          ],
          candy: [
            "from-fuchsia-500 to-pink-500",
            "hover:from-fuchsia-600 hover:to-pink-600",
            "active:from-fuchsia-700 active:to-pink-700",
          ],
          rosebud: [
            "from-pink-500 to-rose-500",
            "hover:from-pink-600 hover:to-rose-600",
            "active:from-pink-700 active:to-rose-700",
          ],
          poppy: [
            "from-rose-400 to-red-500",
            "hover:from-rose-500 hover:to-red-600",
            "active:from-rose-600 active:to-red-700",
          ],
        },
        outline: {
          info: [
            "border-black",
            "text-black",
            "hover:bg-black",
            "hover:text-white",
            "active:bg-info-900",
            "active:border-info-900",
            "active:text-white",
            "dark:border-white",
            "dark:text-white",
            "dark:hover:bg-white",
            "dark:border-white",
            "dark:hover:text-black",
            "dark:active:bg-info-700",
            "dark:active:border-info-700",
            "dark:active:text-white",
            "disabled:bg-info-100",
            "disabled:text-info-300",
            "disabled:border-info-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-info-300",
            "dark:disabled:text-info-300",
          ],
          danger: [
            "border-danger-600",
            "text-danger-600",
            "hover:bg-danger-600",
            "hover:text-white",
            "active:bg-danger-700",
            "active:border-danger-700",
            "active:text-white",
            "dark:border-danger-500",
            "dark:text-danger-500",
            "dark:hover:bg-danger-600",
            "dark:border-danger-600",
            "dark:hover:text-white",
            "dark:active:bg-danger-700",
            "dark:active:border-danger-700",
            "dark:active:text-white",
            "disabled:bg-danger-100",
            "disabled:text-danger-300",
            "disabled:border-danger-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-danger-300",
            "dark:disabled:text-danger-300",
          ],
          primary: [
            "border-primary-600",
            "text-primary-600",
            "hover:bg-primary-600",
            "hover:text-white",
            "active:bg-primary-700",
            "active:border-primary-700",
            "active:text-white",
            "dark:border-primary-500",
            "dark:text-primary-500",
            "dark:hover:bg-primary-600",
            "dark:border-primary-600",
            "dark:hover:text-white",
            "dark:active:bg-primary-700",
            "dark:active:border-primary-700",
            "dark:active:text-white",
            "disabled:bg-primary-100",
            "disabled:text-primary-300",
            "disabled:border-primary-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-primary-300",
            "dark:disabled:text-primary-300",
          ],
          success: [
            "border-success-600",
            "text-success-600",
            "hover:bg-success-600",
            "hover:text-white",
            "active:bg-success-700",
            "active:border-success-700",
            "active:text-white",
            "dark:border-success-500",
            "dark:text-success-500",
            "dark:hover:bg-success-600",
            "dark:border-success-600",
            "dark:hover:text-white",
            "dark:active:bg-success-700",
            "dark:active:border-success-700",
            "dark:active:text-white",
            "disabled:bg-success-100",
            "disabled:text-success-300",
            "disabled:border-success-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-success-300",
            "dark:disabled:text-success-300",
          ],
          warning: [
            "border-warning-600",
            "text-warning-600",
            "hover:bg-warning-600",
            "hover:text-white",
            "active:bg-warning-700",
            "active:border-warning-700",
            "active:text-white",
            "dark:border-warning-500",
            "dark:text-warning-500",
            "dark:hover:bg-warning-600",
            "dark:border-warning-600",
            "dark:hover:text-white",
            "dark:active:bg-warning-700",
            "dark:active:border-warning-700",
            "dark:active:text-white",
            "disabled:bg-warning-100",
            "disabled:text-warning-300",
            "disabled:border-warning-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-warning-300",
            "dark:disabled:text-warning-300",
          ],
          japanese: [
            "border-japanese-600",
            "text-japanese-600",
            "hover:bg-japanese-600",
            "hover:text-white",
            "active:bg-japanese-700",
            "active:border-japanese-700",
            "active:text-white",
            "dark:border-japanese-500",
            "dark:text-japanese-500",
            "dark:hover:bg-japanese-600",
            "dark:border-japanese-600",
            "dark:hover:text-white",
            "dark:active:bg-japanese-700",
            "dark:active:border-japanese-700",
            "dark:active:text-white",
            "disabled:bg-japanese-100",
            "disabled:text-japanese-300",
            "disabled:border-japanese-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-japanese-300",
            "dark:disabled:text-japanese-300",
          ],
          slate: [
            "border-slate-600",
            "text-slate-600",
            "hover:bg-slate-600",
            "hover:text-white",
            "active:bg-slate-700",
            "active:border-slate-700",
            "active:text-white",
            "dark:border-slate-500",
            "dark:text-slate-500",
            "dark:hover:bg-slate-600",
            "dark:border-slate-600",
            "dark:hover:text-white",
            "dark:active:bg-slate-700",
            "dark:active:border-slate-700",
            "dark:active:text-white",
            "disabled:bg-slate-100",
            "disabled:text-slate-300",
            "disabled:border-slate-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-slate-300",
            "dark:disabled:text-slate-300",
          ],
          gray: [
            "border-gray-600",
            "text-gray-600",
            "hover:bg-gray-600",
            "hover:text-white",
            "active:bg-gray-700",
            "active:border-gray-700",
            "active:text-white",
            "dark:border-gray-500",
            "dark:text-gray-500",
            "dark:hover:bg-gray-600",
            "dark:border-gray-600",
            "dark:hover:text-white",
            "dark:active:bg-gray-700",
            "dark:active:border-gray-700",
            "dark:active:text-white",
            "disabled:bg-gray-100",
            "disabled:text-gray-300",
            "disabled:border-gray-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-gray-300",
            "dark:disabled:text-gray-300",
          ],
          zinc: [
            "border-zinc-600",
            "text-zinc-600",
            "hover:bg-zinc-600",
            "hover:text-white",
            "active:bg-zinc-700",
            "active:border-zinc-700",
            "active:text-white",
            "dark:border-zinc-500",
            "dark:text-zinc-500",
            "dark:hover:bg-zinc-600",
            "dark:border-zinc-600",
            "dark:hover:text-white",
            "dark:active:bg-zinc-700",
            "dark:active:border-zinc-700",
            "dark:active:text-white",
            "disabled:bg-zinc-100",
            "disabled:text-zinc-300",
            "disabled:border-zinc-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-zinc-300",
            "dark:disabled:text-zinc-300",
          ],
          neutral: [
            "border-neutral-600",
            "text-neutral-600",
            "hover:bg-neutral-600",
            "hover:text-white",
            "active:bg-neutral-700",
            "active:border-neutral-700",
            "active:text-white",
            "dark:border-neutral-500",
            "dark:text-neutral-500",
            "dark:hover:bg-neutral-600",
            "dark:border-neutral-600",
            "dark:hover:text-white",
            "dark:active:bg-neutral-700",
            "dark:active:border-neutral-700",
            "dark:active:text-white",
            "disabled:bg-neutral-100",
            "disabled:text-neutral-300",
            "disabled:border-neutral-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-neutral-300",
            "dark:disabled:text-neutral-300",
          ],
          stone: [
            "border-stone-600",
            "text-stone-600",
            "hover:bg-stone-600",
            "hover:text-white",
            "active:bg-stone-700",
            "active:border-stone-700",
            "active:text-white",
            "dark:border-stone-500",
            "dark:text-stone-500",
            "dark:hover:bg-stone-600",
            "dark:border-stone-600",
            "dark:hover:text-white",
            "dark:active:bg-stone-700",
            "dark:active:border-stone-700",
            "dark:active:text-white",
            "disabled:bg-stone-100",
            "disabled:text-stone-300",
            "disabled:border-stone-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-stone-300",
            "dark:disabled:text-stone-300",
          ],
          red: [
            "border-red-600",
            "text-red-600",
            "hover:bg-red-600",
            "hover:text-white",
            "active:bg-red-700",
            "active:border-red-700",
            "active:text-white",
            "dark:border-red-500",
            "dark:text-red-500",
            "dark:hover:bg-red-600",
            "dark:border-red-600",
            "dark:hover:text-white",
            "dark:active:bg-red-700",
            "dark:active:border-red-700",
            "dark:active:text-white",
            "disabled:bg-red-100",
            "disabled:text-red-300",
            "disabled:border-red-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-red-300",
            "dark:disabled:text-red-300",
          ],
          orange: [
            "border-orange-600",
            "text-orange-600",
            "hover:bg-orange-600",
            "hover:text-white",
            "active:bg-orange-700",
            "active:border-orange-700",
            "active:text-white",
            "dark:border-orange-500",
            "dark:text-orange-500",
            "dark:hover:bg-orange-600",
            "dark:border-orange-600",
            "dark:hover:text-white",
            "dark:active:bg-orange-700",
            "dark:active:border-orange-700",
            "dark:active:text-white",
            "disabled:bg-orange-100",
            "disabled:text-orange-300",
            "disabled:border-orange-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-orange-300",
            "dark:disabled:text-orange-300",
          ],
          amber: [
            "border-amber-600",
            "text-amber-600",
            "hover:bg-amber-600",
            "hover:text-white",
            "active:bg-amber-700",
            "active:border-amber-700",
            "active:text-white",
            "dark:border-amber-500",
            "dark:text-amber-500",
            "dark:hover:bg-amber-600",
            "dark:border-amber-600",
            "dark:hover:text-white",
            "dark:active:bg-amber-700",
            "dark:active:border-amber-700",
            "dark:active:text-white",
            "disabled:bg-amber-100",
            "disabled:text-amber-300",
            "disabled:border-amber-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-amber-300",
            "dark:disabled:text-amber-300",
          ],
          yellow: [
            "border-yellow-600",
            "text-yellow-600",
            "hover:bg-yellow-600",
            "hover:text-white",
            "active:bg-yellow-700",
            "active:border-yellow-700",
            "active:text-white",
            "dark:border-yellow-500",
            "dark:text-yellow-500",
            "dark:hover:bg-yellow-600",
            "dark:border-yellow-600",
            "dark:hover:text-white",
            "dark:active:bg-yellow-700",
            "dark:active:border-yellow-700",
            "dark:active:text-white",
            "disabled:bg-yellow-100",
            "disabled:text-yellow-300",
            "disabled:border-yellow-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-yellow-300",
            "dark:disabled:text-yellow-300",
          ],
          lime: [
            "border-lime-600",
            "text-lime-600",
            "hover:bg-lime-600",
            "hover:text-white",
            "active:bg-lime-700",
            "active:border-lime-700",
            "active:text-white",
            "dark:border-lime-500",
            "dark:text-lime-500",
            "dark:hover:bg-lime-600",
            "dark:border-lime-600",
            "dark:hover:text-white",
            "dark:active:bg-lime-700",
            "dark:active:border-lime-700",
            "dark:active:text-white",
            "disabled:bg-lime-100",
            "disabled:text-lime-300",
            "disabled:border-lime-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-lime-300",
            "dark:disabled:text-lime-300",
          ],
          green: [
            "border-green-600",
            "text-green-600",
            "hover:bg-green-600",
            "hover:text-white",
            "active:bg-green-700",
            "active:border-green-700",
            "active:text-white",
            "dark:border-green-500",
            "dark:text-green-500",
            "dark:hover:bg-green-600",
            "dark:border-green-600",
            "dark:hover:text-white",
            "dark:active:bg-green-700",
            "dark:active:border-green-700",
            "dark:active:text-white",
            "disabled:bg-green-100",
            "disabled:text-green-300",
            "disabled:border-green-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-green-300",
            "dark:disabled:text-green-300",
          ],
          emerald: [
            "border-emerald-600",
            "text-emerald-600",
            "hover:bg-emerald-600",
            "hover:text-white",
            "active:bg-emerald-700",
            "active:border-emerald-700",
            "active:text-white",
            "dark:border-emerald-500",
            "dark:text-emerald-500",
            "dark:hover:bg-emerald-600",
            "dark:border-emerald-600",
            "dark:hover:text-white",
            "dark:active:bg-emerald-700",
            "dark:active:border-emerald-700",
            "dark:active:text-white",
            "disabled:bg-emerald-100",
            "disabled:text-emerald-300",
            "disabled:border-emerald-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-emerald-300",
            "dark:disabled:text-emerald-300",
          ],
          teal: [
            "border-teal-600",
            "text-teal-600",
            "hover:bg-teal-600",
            "hover:text-white",
            "active:bg-teal-700",
            "active:border-teal-700",
            "active:text-white",
            "dark:border-teal-500",
            "dark:text-teal-500",
            "dark:hover:bg-teal-600",
            "dark:border-teal-600",
            "dark:hover:text-white",
            "dark:active:bg-teal-700",
            "dark:active:border-teal-700",
            "dark:active:text-white",
            "disabled:bg-teal-100",
            "disabled:text-teal-300",
            "disabled:border-teal-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-teal-300",
            "dark:disabled:text-teal-300",
          ],
          cyan: [
            "border-cyan-600",
            "text-cyan-600",
            "hover:bg-cyan-600",
            "hover:text-white",
            "active:bg-cyan-700",
            "active:border-cyan-700",
            "active:text-white",
            "dark:border-cyan-500",
            "dark:text-cyan-500",
            "dark:hover:bg-cyan-600",
            "dark:border-cyan-600",
            "dark:hover:text-white",
            "dark:active:bg-cyan-700",
            "dark:active:border-cyan-700",
            "dark:active:text-white",
            "disabled:bg-cyan-100",
            "disabled:text-cyan-300",
            "disabled:border-cyan-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-cyan-300",
            "dark:disabled:text-cyan-300",
          ],
          sky: [
            "border-sky-600",
            "text-sky-600",
            "hover:bg-sky-600",
            "hover:text-white",
            "active:bg-sky-700",
            "active:border-sky-700",
            "active:text-white",
            "dark:border-sky-500",
            "dark:text-sky-500",
            "dark:hover:bg-sky-600",
            "dark:border-sky-600",
            "dark:hover:text-white",
            "dark:active:bg-sky-700",
            "dark:active:border-sky-700",
            "dark:active:text-white",
            "disabled:bg-sky-100",
            "disabled:text-sky-300",
            "disabled:border-sky-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-sky-300",
            "dark:disabled:text-sky-300",
          ],
          blue: [
            "border-blue-600",
            "text-blue-600",
            "hover:bg-blue-600",
            "hover:text-white",
            "active:bg-blue-700",
            "active:border-blue-700",
            "active:text-white",
            "dark:border-blue-500",
            "dark:text-blue-500",
            "dark:hover:bg-blue-600",
            "dark:border-blue-600",
            "dark:hover:text-white",
            "dark:active:bg-blue-700",
            "dark:active:border-blue-700",
            "dark:active:text-white",
            "disabled:bg-blue-100",
            "disabled:text-blue-300",
            "disabled:border-blue-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-blue-300",
            "dark:disabled:text-blue-300",
          ],
          indigo: [
            "border-indigo-600",
            "text-indigo-600",
            "hover:bg-indigo-600",
            "hover:text-white",
            "active:bg-indigo-700",
            "active:border-indigo-700",
            "active:text-white",
            "dark:border-indigo-500",
            "dark:text-indigo-500",
            "dark:hover:bg-indigo-600",
            "dark:border-indigo-600",
            "dark:hover:text-white",
            "dark:active:bg-indigo-700",
            "dark:active:border-indigo-700",
            "dark:active:text-white",
            "disabled:bg-indigo-100",
            "disabled:text-indigo-300",
            "disabled:border-indigo-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-indigo-300",
            "dark:disabled:text-indigo-300",
          ],
          violet: [
            "border-violet-600",
            "text-violet-600",
            "hover:bg-violet-600",
            "hover:text-white",
            "active:bg-violet-700",
            "active:border-violet-700",
            "active:text-white",
            "dark:border-violet-500",
            "dark:text-violet-500",
            "dark:hover:bg-violet-600",
            "dark:border-violet-600",
            "dark:hover:text-white",
            "dark:active:bg-violet-700",
            "dark:active:border-violet-700",
            "dark:active:text-white",
            "disabled:bg-violet-100",
            "disabled:text-violet-300",
            "disabled:border-violet-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-violet-300",
            "dark:disabled:text-violet-300",
          ],
          purple: [
            "border-purple-600",
            "text-purple-600",
            "hover:bg-purple-600",
            "hover:text-white",
            "active:bg-purple-700",
            "active:border-purple-700",
            "active:text-white",
            "dark:border-purple-500",
            "dark:text-purple-500",
            "dark:hover:bg-purple-600",
            "dark:border-purple-600",
            "dark:hover:text-white",
            "dark:active:bg-purple-700",
            "dark:active:border-purple-700",
            "dark:active:text-white",
            "disabled:bg-purple-100",
            "disabled:text-purple-300",
            "disabled:border-purple-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-purple-300",
            "dark:disabled:text-purple-300",
          ],
          fuchsia: [
            "border-fuchsia-600",
            "text-fuchsia-600",
            "hover:bg-fuchsia-600",
            "hover:text-white",
            "active:bg-fuchsia-700",
            "active:border-fuchsia-700",
            "active:text-white",
            "dark:border-fuchsia-500",
            "dark:text-fuchsia-500",
            "dark:hover:bg-fuchsia-600",
            "dark:border-fuchsia-600",
            "dark:hover:text-white",
            "dark:active:bg-fuchsia-700",
            "dark:active:border-fuchsia-700",
            "dark:active:text-white",
            "disabled:bg-fuchsia-100",
            "disabled:text-fuchsia-300",
            "disabled:border-fuchsia-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-fuchsia-300",
            "dark:disabled:text-fuchsia-300",
          ],
          pink: [
            "border-pink-600",
            "text-pink-600",
            "hover:bg-pink-600",
            "hover:text-white",
            "active:bg-pink-700",
            "active:border-pink-700",
            "active:text-white",
            "dark:border-pink-500",
            "dark:text-pink-500",
            "dark:hover:bg-pink-600",
            "dark:border-pink-600",
            "dark:hover:text-white",
            "dark:active:bg-pink-700",
            "dark:active:border-pink-700",
            "dark:active:text-white",
            "disabled:bg-pink-100",
            "disabled:text-pink-300",
            "disabled:border-pink-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-pink-300",
            "dark:disabled:text-pink-300",
          ],
          rose: [
            "border-rose-600",
            "text-rose-600",
            "hover:bg-rose-600",
            "hover:text-white",
            "active:bg-rose-700",
            "active:border-rose-700",
            "active:text-white",
            "dark:border-rose-500",
            "dark:text-rose-500",
            "dark:hover:bg-rose-600",
            "dark:border-rose-600",
            "dark:hover:text-white",
            "dark:active:bg-rose-700",
            "dark:active:border-rose-700",
            "dark:active:text-white",
            "disabled:bg-rose-100",
            "disabled:text-rose-300",
            "disabled:border-rose-300",
            "dark:disabled:bg-inherit",
            "dark:disabled:border-rose-300",
            "dark:disabled:text-rose-300",
          ],
        },
      },
      defaultVariants: {
        shape: "default",
      },
    }
  );
  return (
    <button
      className={twMerge(
        StyleButton({
          width,
          height,
          px,
          toggle,
          mode,
          gap,
          size,
          shape,
          outline,
          variant,
          bezel,
        }),
        className
      )}
      onClick={onClick}
      disabled={disabled}
      type={type}
      {...props}
    >
      {icon ? <span>{icon}</span> : null}
      {loading ? <span>{loading}</span> : null}
      {chidlren}
      {value}
      {arrow ? <span>{arrow}</span> : null}
    </button>
  );
};

export default Button;
